version: '3'
services:
#Création d'un conteneur avec un serveur de base de données.
  db:
    image: mysql
    container_name: ${MYSQL_HOST}
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PWD}
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: acosson
      MYSQL_PASSWORD: 'acosson'
    volumes:
#Permet de charger automatiquement le script qui se situe dans le dossier scripts.
      - "./scripts:/docker-entrypoint-initdb.d"
#Création d'un conteneur avec phpmyadmin afin de gérer le serveur de base de données.
  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8080:80
#Création d'un serveur web
  webserver:
    image: 'nginx:alpine'
    working_dir: /application
    volumes:
      - '.:/application'
      - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
    ports:
      - '14540:80'
  #Création d'un module php
  php-fpm:
        build: phpdocker/php-fpm
        working_dir: /application
        volumes:
            - '.:/application'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini'
  #Définition des variables d'environnements nécessaires aux composants d'accès aux données.
        environment:
          - MYSQL_HOST=${MYSQL_HOST}
          - MYSQL_PWD=${MYSQL_PWD}
          - MYSQL_USER=${MYSQL_USER}
          - MYSQL_DB=${MYSQL_DB}



